services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizuser -d quizzes || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizuser
      POSTGRES_PASSWORD: quizpass
      POSTGRES_DB: quizzes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://quizuser:quizpass@db:5432/quizzes?schema=public
      PORT: 4000
      JWT_ACCESS_SECRET: super_access_secret_change_me
      JWT_REFRESH_SECRET: super_refresh_secret_change_me
      CORS_ORIGIN: http://localhost:5173
      NODE_ENV: production
    ports:
      - "4000:4000"

  web:
    build: ./apps/web
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"

volumes:
  db_data:
